<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ubuntu" name="org.openqa.demo.nodes.service.WebDriverValidationService" tests="2" failures="1" timestamp="8 Jun 2011 11:24:39 GMT" time="6.869" errors="0">
  <testcase name="test" time="6.699" classname="org.openqa.demo.nodes.service.WebDriverValidationService"/>
  <testcase name="test" time="0.170" classname="org.openqa.demo.nodes.service.WebDriverValidationService">
    <failure type="com.opera.core.systems.runner.OperaRunnerException" message="Unable to listen to opera launcher port 9999">
      <![CDATA[com.opera.core.systems.runner.OperaRunnerException: Unable to listen to opera launcher port 9999
	at com.opera.core.systems.runner.launcher.OperaLauncherRunner.<init>(OperaLauncherRunner.java:158)
	at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:138)
	at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:105)
	at org.openqa.demo.nodes.service.WebDriverValidationService.test(WebDriverValidationService.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:81)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:636)
Caused by: java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
	at java.net.ServerSocket.bind(ServerSocket.java:336)
	at java.net.ServerSocket.<init>(ServerSocket.java:202)
	at java.net.ServerSocket.<init>(ServerSocket.java:114)
	at com.opera.core.systems.runner.launcher.OperaLauncherRunner.<init>(OperaLauncherRunner.java:130)
	... 17 more
]]>
    </failure>
  </testcase>
</testsuite>
